// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

// lv_font_fmt_txt_dsc_t font_dsc = {
//     .glyph_bitmap = glyph_bitmap,
//     .glyph_dsc = glyph_dsc,
//     .cmaps = cmaps,
//     .kern_dsc = &kern_classes,
//     .kern_scale = 16,
//     .cmap_num = 2,
//     .bpp = 4,
//     .kern_classes = 1,
//     .bitmap_format = 0,

// };

// lv_font_t lv_font_montserrat_30 = {
// // #endif
//     .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
//     .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
//     .line_height = 33,          /*The maximum line height required by the font*/
//     .base_line = 6,             /*Baseline measured from the bottom of the line*/
// // #if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
//     .subpx = LV_FONT_SUBPX_NONE,
// // #endif
// // #if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
//     .underline_position = -2,
//     .underline_thickness = 2,
// // #endif
//     // .dsc = &font_dsc           /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc` */
// };

void ui_p3d_event(lv_event_t * e);


void ui_dcs_event(lv_event_t * e);


void ui_f16_event(lv_event_t * e);


void ui_f18_event(lv_event_t * e);


void ui_f22_event(lv_event_t * e);
void game_screen_init(void){
    game_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(game_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(game_screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(game_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_p3d = lv_obj_create(game_screen);
    lv_obj_remove_style_all(ui_container_p3d);
    lv_obj_set_width(ui_container_p3d, 130);
    lv_obj_set_height(ui_container_p3d, 70);
    lv_obj_set_x(ui_container_p3d, -83);
    lv_obj_set_y(ui_container_p3d, -98);
    lv_obj_set_align(ui_container_p3d, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_p3d, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_p3d, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_p3d, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_p3d, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_container_p3d, lv_color_hex(0xF55C19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_container_p3d, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_container_p3d, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_p3d = lv_label_create(ui_container_p3d);
    lv_obj_set_width(ui_label_p3d, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_p3d, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_p3d, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_p3d, "P3D");
    // lv_obj_set_style_text_font(ui_label_p3d, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_dcs = lv_obj_create(game_screen);
    lv_obj_remove_style_all(ui_container_dcs);
    lv_obj_set_width(ui_container_dcs, 130);
    lv_obj_set_height(ui_container_dcs, 70);
    lv_obj_set_x(ui_container_dcs, 83);
    lv_obj_set_y(ui_container_dcs, -99);
    lv_obj_set_align(ui_container_dcs, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_dcs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_dcs, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_container_dcs, lv_color_hex(0xF55C19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_container_dcs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_container_dcs, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_dcs = lv_label_create(ui_container_dcs);
    lv_obj_set_width(ui_label_dcs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_dcs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_dcs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_dcs, "DCS");
    // lv_obj_set_style_text_font(ui_label_dcs, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_dcs_sub = lv_obj_create(game_screen);
    lv_obj_remove_style_all(ui_container_dcs_sub);
    lv_obj_set_width(ui_container_dcs_sub, 467);
    lv_obj_set_height(ui_container_dcs_sub, 121);
    lv_obj_set_x(ui_container_dcs_sub, 0);
    lv_obj_set_y(ui_container_dcs_sub, 93);
    lv_obj_set_align(ui_container_dcs_sub, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_container_dcs_sub, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_container_dcs_sub, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_container_dcs_sub, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_container_f16 = lv_obj_create(ui_container_dcs_sub);
    lv_obj_remove_style_all(ui_container_f16);
    lv_obj_set_width(ui_container_f16, 138);
    lv_obj_set_height(ui_container_f16, 80);
    lv_obj_set_x(ui_container_f16, 154);
    lv_obj_set_y(ui_container_f16, 92);
    lv_obj_set_align(ui_container_f16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_f16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_f16, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_container_f16, lv_color_hex(0xF55C19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_container_f16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_container_f16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_f16 = lv_label_create(ui_container_f16);
    lv_obj_set_width(ui_label_f16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_f16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_f16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_f16, "F16");
    // lv_obj_set_style_text_font(ui_label_f16, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_f18 = lv_obj_create(ui_container_dcs_sub);
    lv_obj_remove_style_all(ui_container_f18);
    lv_obj_set_width(ui_container_f18, 138);
    lv_obj_set_height(ui_container_f18, 80);
    lv_obj_set_x(ui_container_f18, -4);
    lv_obj_set_y(ui_container_f18, 88);
    lv_obj_set_align(ui_container_f18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_f18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_f18, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_container_f18, lv_color_hex(0xF55C19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_container_f18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_container_f18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_f18 = lv_label_create(ui_container_f18);
    lv_obj_set_width(ui_label_f18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_f18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_f18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_f18, "F18");
    // lv_obj_set_style_text_font(ui_label_f18, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_f22 = lv_obj_create(ui_container_dcs_sub);
    lv_obj_remove_style_all(ui_container_f22);
    lv_obj_set_width(ui_container_f22, 138);
    lv_obj_set_height(ui_container_f22, 80);
    lv_obj_set_x(ui_container_f22, -157);
    lv_obj_set_y(ui_container_f22, 88);
    lv_obj_set_align(ui_container_f22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_f22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_f22, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_container_f22, lv_color_hex(0xF55C19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_container_f22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_container_f22, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_f22 = lv_label_create(ui_container_f22);
    lv_obj_set_width(ui_label_f22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_f22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_f22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_f22, "F22");
    // lv_obj_set_style_text_font(ui_label_f22, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button_return = lv_button_create(game_screen);
    lv_obj_set_width(ui_button_return, 100);
    lv_obj_set_height(ui_button_return, 50);
    lv_obj_set_x(ui_button_return, -161);
    lv_obj_set_y(ui_button_return, -205);
    lv_obj_set_align(ui_button_return, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button_return, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_button_return, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_return = lv_label_create(ui_button_return);
    lv_obj_set_width(ui_label_return, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_return, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_return, 1);
    lv_obj_set_y(ui_label_return, 4);
    lv_obj_set_align(ui_label_return, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_return, "返回");
    lv_obj_set_style_text_font(ui_label_return, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button_return, ui_event_button_game_return, LV_EVENT_ALL, NULL);
    ui_p3d = ui_container_p3d;
    ui_dcs = ui_container_dcs;
    ui_f16 = ui_container_f16;
    ui_f18 = ui_container_f18;
    ui_f22 = ui_container_f22;

    lv_obj_set_style_bg_opa(ui_f16, LV_OPA_COVER,LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_f18, LV_OPA_COVER,LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_f22, LV_OPA_COVER,LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dcs, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);


    //链接游戏选择的界面
    lv_obj_add_event_cb(ui_p3d, ui_p3d_event, LV_EVENT_ALL, NULL);//p3d那个按钮回调，下边同理
    lv_obj_add_event_cb(ui_dcs, ui_dcs_event, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_f16, ui_f16_event, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_f18, ui_f18_event, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_f22, ui_f22_event, LV_EVENT_ALL, NULL);


}
void ui_p3d_event(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED) {
        //点击P3D按钮之后将P3D按钮设置成黄色 dcs设置透明 同事删除ui_Container14（dcs里面的三个选项）
        lv_obj_set_style_bg_color(ui_p3d, lv_color_hex(0xF66D31), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_dcs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_add_flag(ui_container_dcs_sub, LV_OBJ_FLAG_HIDDEN);

    }

}


void ui_dcs_event(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED) {
        //点击DCS按钮之后将DCS按钮设置成黄色 P3D设置透明 同事显示ui_Container14（dcs里面的三个选项）
        lv_obj_set_style_bg_color(ui_p3d, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_dcs, lv_color_hex(0xF66D31), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_clear_flag(ui_container_dcs_sub, LV_OBJ_FLAG_HIDDEN);


    }

}


void ui_f16_event(lv_event_t * e){

    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
    //点击f16按钮 将f16设置成黄色 其他设置成白色  下边两个回调同理，其他页面的这个回调函数同理 都是点击按钮将按钮设置黄色其他设置为白色
        lv_obj_set_style_bg_color(ui_f16, lv_color_hex(0xF66D31), LV_PART_MAIN|LV_STATE_DEFAULT  );
        lv_obj_set_style_bg_color(ui_f18, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT );
         lv_obj_set_style_bg_color(ui_f22, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT );
      
    }

}


void ui_f18_event(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        lv_obj_set_style_bg_color(ui_f16, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT  );
        lv_obj_set_style_bg_color(ui_f18, lv_color_hex(0xF66D31), LV_PART_MAIN|LV_STATE_DEFAULT );
         lv_obj_set_style_bg_color(ui_f22, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT );
      
    }

}


void ui_f22_event(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        lv_obj_set_style_bg_color(ui_f16, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT  );
        lv_obj_set_style_bg_color(ui_f18, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT );
        lv_obj_set_style_bg_color(ui_f22, lv_color_hex(0xF66D31), LV_PART_MAIN|LV_STATE_DEFAULT );
      
    }

}
