// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void main_screen_init(void)
{
    main_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(main_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(main_screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(main_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_game = lv_obj_create(main_screen);
    lv_obj_remove_style_all(ui_container_game);
    lv_obj_set_width(ui_container_game, 331);
    lv_obj_set_height(ui_container_game, 78);
    lv_obj_set_x(ui_container_game, 2);
    lv_obj_set_y(ui_container_game, -107);
    lv_obj_set_align(ui_container_game, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_game, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_game, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_game, lv_color_hex(0x439EA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_game, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_game = lv_label_create(ui_container_game);
    lv_obj_set_width(ui_label_game, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_game, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_game, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_game, "连接游戏选择 >>");
    lv_obj_set_style_text_color(ui_label_game, lv_color_hex(0xF8F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_game, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_game, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_ui_config = lv_obj_create(main_screen);
    lv_obj_remove_style_all(ui_container_ui_config);
    lv_obj_set_width(ui_container_ui_config, 331);
    lv_obj_set_height(ui_container_ui_config, 78);
    lv_obj_set_x(ui_container_ui_config, 5);
    lv_obj_set_y(ui_container_ui_config, 133);
    lv_obj_set_align(ui_container_ui_config, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_ui_config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_ui_config, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_ui_config, lv_color_hex(0x29CB47), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_ui_config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_ui_config = lv_label_create(ui_container_ui_config);
    lv_obj_set_width(ui_label_ui_config, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_ui_config, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_ui_config, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_ui_config, "UI设置 >>");
    lv_obj_set_style_text_color(ui_label_ui_config, lv_color_hex(0xF8F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_ui_config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_ui_config, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_sensor = lv_obj_create(main_screen);
    lv_obj_remove_style_all(ui_container_sensor);
    lv_obj_set_width(ui_container_sensor, 331);
    lv_obj_set_height(ui_container_sensor, 78);
    lv_obj_set_x(ui_container_sensor, 2);
    lv_obj_set_y(ui_container_sensor, 12);
    lv_obj_set_align(ui_container_sensor, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_sensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_sensor, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_sensor, lv_color_hex(0xD84BB0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_sensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_sensor = lv_label_create(ui_container_sensor);
    lv_obj_set_width(ui_label_sensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_sensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_sensor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_sensor, "传感器设置 >>");
    lv_obj_set_style_text_color(ui_label_sensor, lv_color_hex(0xF8F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_sensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_sensor, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_return = lv_obj_create(main_screen);
    lv_obj_remove_style_all(ui_container_return);
    lv_obj_set_width(ui_container_return, 100);
    lv_obj_set_height(ui_container_return, 50);
    lv_obj_set_align(ui_container_return, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_return, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button_return = lv_button_create(main_screen);
    lv_obj_set_width(ui_button_return, 100);
    lv_obj_set_height(ui_button_return, 50);
    lv_obj_set_x(ui_button_return, -161);
    lv_obj_set_y(ui_button_return, -205);
    lv_obj_set_align(ui_button_return, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button_return, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_button_return, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_return = lv_label_create(ui_button_return);
    lv_obj_set_width(ui_label_return, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_return, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_return, 1);
    lv_obj_set_y(ui_label_return, 4);
    lv_obj_set_align(ui_label_return, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_return, "返回");
    lv_obj_set_style_text_font(ui_label_return, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_container_game, ui_event_game, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_container_ui_config, ui_event_ui_config, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_container_sensor, ui_event_sensor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_return, ui_event_button_main_return, LV_EVENT_ALL, NULL);
    ui_game_chose = ui_container_game;
    ui_ui_select = ui_label_ui_config;
    ui_sensor_select = ui_container_sensor;

}
