/** -------------------- By MiluoOffical 2026.02.02 --------------
 * @file red_screen.cpp
 * @date 2026-02-02
 * @note 本文件原本为 red_screen.c
 *       为了能在该处进行红屏操作和红屏进入/退出, 需要访问gfx类, 而gfx类为C++对象, 无法在c源文件中使用
 *       因此需要更名
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

extern "C" {
#include "core/lv_obj_pos.h"
#include "core/lv_refr.h"
#include "display/lv_display.h"
#include "ui.h"
#include "ui_helpers.h" // 为了 _ui_screen_change 函数
}
#include <Arduino_GFX_Library.h>

#include "gesture-rgb.h"
#include "receive-mpu.h"
#include "receive-mavlink.h"

extern Arduino_DSI_Display *gfx; //显示句柄

ges_data_t ges_data_red;

static int redScreenStatus = false;
static bool redScreenUpdated = false;


extern "C" void showRedScreen(){
    drawGestureByData(2, ges_data_red, 0, 0);
    redScreenStatus = true;
}

extern "C" void lvglHandler(){
    if(redScreenStatus){
        if(!redScreenUpdated){
            drawGestureByData(2, ges_data_red, 0, 0);
            redScreenUpdated = true;
        }
    }
    else{
        lv_timer_handler();
    }
}

extern "C" void clearRedScreen(){
    redScreenStatus = false;
    redScreenUpdated = false;
    _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    lv_obj_update_layout(main_screen);
    lv_area_t mainArea = {
        .x1 = 0,
        .y1 = 0,
        .x2 = lv_obj_get_width(main_screen),
        .y2 = lv_obj_get_height(main_screen),
    };
    lv_obj_invalidate_area(main_screen, &mainArea);
    lv_refr_now(lv_display_get_default());
}

extern "C" bool isRedScreen(){
    return redScreenStatus;
}

// extern "C" void red_screen_init(void){ //这个函数是C接口的 所以加上 extern "C"
//     red_screen = lv_obj_create(NULL);
//     lv_obj_remove_flag(red_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(red_screen, lv_color_hex(0xFA0303), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(red_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container19 = lv_obj_create(red_screen);
//     lv_obj_remove_style_all(ui_Container19);
//     lv_obj_set_width(ui_Container19, 100);
//     lv_obj_set_height(ui_Container19, 50);
//     lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
//     lv_obj_remove_flag(ui_Container19, lv_obj_flag_t (LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));      /// Flags

//     lv_obj_add_event_cb(red_screen, ui_event_bottom_slide_up, LV_EVENT_ALL, NULL);

// }
