// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void main_screen_init(void);
lv_obj_t * main_screen;
void ui_event_game(lv_event_t * e);
lv_obj_t * ui_container_game;
lv_obj_t * ui_label_game;
void ui_event_ui_config(lv_event_t * e);
lv_obj_t * ui_container_ui_config;
lv_obj_t * ui_label_ui_config;
void ui_event_sensor(lv_event_t * e);
lv_obj_t * ui_container_sensor;
lv_obj_t * ui_label_sensor;
lv_obj_t * ui_container_return;
void ui_event_button_main_return(lv_event_t * e);
lv_obj_t * ui_button_return;
lv_obj_t * ui_label_return;
// CUSTOM VARIABLES
lv_obj_t * ui_game_chose;
lv_obj_t * ui_ui_select;
lv_obj_t * ui_sensor_select;


// SCREEN: ui_Screen2
void game_screen_init(void);
lv_obj_t * game_screen;
lv_obj_t * ui_container_p3d;
lv_obj_t * ui_label_p3d;
lv_obj_t * ui_container_dcs;
lv_obj_t * ui_label_dcs;
lv_obj_t * ui_container_dcs_sub;
lv_obj_t * ui_container_f16;
lv_obj_t * ui_label_f16;
lv_obj_t * ui_container_f18;
lv_obj_t * ui_label_f18;
lv_obj_t * ui_container_f22;
lv_obj_t * ui_label_f22;
void ui_event_button_game_return(lv_event_t * e);
lv_obj_t * ui_button_return;
lv_obj_t * ui_label_return;
// CUSTOM VARIABLES
lv_obj_t * ui_p3d;
lv_obj_t * ui_dcs;
lv_obj_t * ui_f16;
lv_obj_t * ui_f18;
lv_obj_t * ui_f22;


// SCREEN: sensor_screen
void sensor_screen_init(void);
lv_obj_t * sensor_screen;
void ui_event_button_sensor_return(lv_event_t * e);
lv_obj_t * ui_button_return;
lv_obj_t * ui_label_return;
lv_obj_t * ui_container_gyro;
lv_obj_t * ui_label_gyro;
lv_obj_t * ui_container_feikong;
lv_obj_t * ui_label_feikong;
// CUSTOM VARIABLES
lv_obj_t * ui_gyro;
lv_obj_t * ui_fc;


// SCREEN: ui_config_screen_init
void ui_config_screen_init(void);
lv_obj_t * ui_config_screen;
lv_obj_t * ui_container_yes;
lv_obj_t * ui_label_yes;
lv_obj_t * ui_container_no;
lv_obj_t * ui_label_no;
lv_obj_t * ui_label_yaw_show;
void ui_event_button_ui_config_return(lv_event_t * e);
lv_obj_t * ui_button_return;
lv_obj_t * ui_label_return;
// CUSTOM VARIABLES
lv_obj_t * ui_yes;
lv_obj_t * ui_no;


// SCREEN: red_screen
// void red_screen_init(void);
void ui_event_bottom_slide_up(lv_event_t * e);
lv_obj_t * red_screen;
lv_obj_t * ui_Container19;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
   // #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_game(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&game_screen, LV_SCR_LOAD_ANIM_FADE_ON, 11, 0, &game_screen_init);
    }
}

void ui_event_ui_config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_config_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &ui_config_screen_init);
    }
}

void ui_event_sensor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&sensor_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &sensor_screen_init);
    }
}

void ui_event_button_main_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // ESP_LOGI("UI_C", "Red screen loaded");
        showRedScreen(); //显示红屏
        //_ui_screen_change(&red_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &red_screen_init);
    }
}

void ui_event_button_game_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    }
}

void ui_event_button_sensor_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    }
}

void ui_event_button_ui_config_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    }
}

void ui_event_bottom_slide_up(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &main_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void){
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    main_screen_init();
    game_screen_init();
    sensor_screen_init();
    ui_config_screen_init();
    // red_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(main_screen);
}
