// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void main_screen_init(void);
lv_obj_t * main_screen;
void ui_event_game(lv_event_t * e);
lv_obj_t * ui_game;
lv_obj_t * ui_Label1;
void ui_event_Container3(lv_event_t * e);
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label3;
void ui_event_Container4(lv_event_t * e);
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Container13;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label21;
// CUSTOM VARIABLES
lv_obj_t * ui_game_chose;
lv_obj_t * ui_ui_select;
lv_obj_t * ui_sensor_select;


// SCREEN: ui_Screen2
void game_screen_init(void);
lv_obj_t * game_screen;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label6;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label14;
// CUSTOM VARIABLES
lv_obj_t * ui_p3d;
lv_obj_t * ui_dcs;
lv_obj_t * ui_f16;
lv_obj_t * ui_f18;
lv_obj_t * ui_f22;


// SCREEN: sensor_screen
void sensor_screen_init(void);
lv_obj_t * sensor_screen;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Container18;
lv_obj_t * ui_Label22;
// CUSTOM VARIABLES
lv_obj_t * ui_gyro;
lv_obj_t * ui_fc;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label18;
// CUSTOM VARIABLES
lv_obj_t * ui_yes;
lv_obj_t * ui_no;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Container19;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
   // #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_game(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&game_screen, LV_SCR_LOAD_ANIM_FADE_ON, 11, 0, &game_screen_init);
    }
}

void ui_event_Container3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Container4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&sensor_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &sensor_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    }
}

void ui_event_Screen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 222, 0, &main_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    main_screen_init();
    game_screen_init();
    sensor_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(main_screen);
}
