// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
// #include "ui_events.h"


// SCREEN: ui_Screen1
void main_screen_init(void);
extern lv_obj_t * main_screen;
void ui_event_game(lv_event_t * e);
extern lv_obj_t * ui_container_game;
extern lv_obj_t * ui_label_game;
void ui_event_ui_config(lv_event_t * e);
extern lv_obj_t * ui_container_ui_config;
extern lv_obj_t * ui_label_ui_config;
void ui_event_sensor(lv_event_t * e);
extern lv_obj_t * ui_container_sensor;
extern lv_obj_t * ui_label_sensor;
extern lv_obj_t * ui_container_return;
void ui_event_button_main_return(lv_event_t * e);
extern lv_obj_t * ui_button_return;
extern lv_obj_t * ui_label_return;
// CUSTOM VARIABLES
extern lv_obj_t * ui_game_chose;
extern lv_obj_t * ui_ui_select;
extern lv_obj_t * ui_sensor_select;

// SCREEN: ui_Screen2
void game_screen_init(void);
extern lv_obj_t * game_screen;
extern lv_obj_t * ui_container_p3d;
extern lv_obj_t * ui_label_p3d;
extern lv_obj_t * ui_container_dcs;
extern lv_obj_t * ui_label_dcs;
extern lv_obj_t * ui_container_dcs_sub;
extern lv_obj_t * ui_container_f16;
extern lv_obj_t * ui_label_f16;
extern lv_obj_t * ui_container_f18;
extern lv_obj_t * ui_label_f18;
extern lv_obj_t * ui_container_f22;
extern lv_obj_t * ui_label_f22;
void ui_event_button_game_return(lv_event_t * e);
extern lv_obj_t * ui_button_return;
extern lv_obj_t * ui_label_return;
// CUSTOM VARIABLES
extern lv_obj_t * ui_p3d;
extern lv_obj_t * ui_dcs;
extern lv_obj_t * ui_f16;
extern lv_obj_t * ui_f18;
extern lv_obj_t * ui_f22;

// SCREEN: ui_Screen3
void sensor_screen_init(void);
extern lv_obj_t * sensor_screen;
void ui_event_button_sensor_return(lv_event_t * e);
extern lv_obj_t * ui_button_return;
extern lv_obj_t * ui_label_return;
extern lv_obj_t * ui_container_gyro;
extern lv_obj_t * ui_label_gyro;
extern lv_obj_t * ui_container_feikong;
extern lv_obj_t * ui_label_feikong;
// CUSTOM VARIABLES
extern lv_obj_t * ui_gyro;
extern lv_obj_t * ui_fc;

// SCREEN: ui_Screen4
void ui_config_screen_init(void);
extern lv_obj_t * ui_config_screen;
extern lv_obj_t * ui_container_yes;
extern lv_obj_t * ui_label_yes;
extern lv_obj_t * ui_container_no;
extern lv_obj_t * ui_label_no;
extern lv_obj_t * ui_label_yaw_show;
void ui_event_button_ui_config_return(lv_event_t * e);
extern lv_obj_t * ui_button_return;
extern lv_obj_t * ui_label_return;
// CUSTOM VARIABLES
extern lv_obj_t * ui_yes;
extern lv_obj_t * ui_no;

// SCREEN: ui_Screen5
void red_screen_init(void);
void ui_event_bottom_slide_up(lv_event_t * e);
extern lv_obj_t * red_screen;
extern lv_obj_t * ui_Container19;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
