// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void main_screen_init(void);
extern lv_obj_t * main_screen;
void ui_event_game(lv_event_t * e);
extern lv_obj_t * ui_game;
extern lv_obj_t * ui_Label1;
void ui_event_Container3(lv_event_t * e);
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label3;
void ui_event_Container4(lv_event_t * e);
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container13;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES
extern lv_obj_t * ui_game_chose;
extern lv_obj_t * ui_ui_select;
extern lv_obj_t * ui_sensor_select;

// SCREEN: ui_Screen2
void game_screen_init(void);
extern lv_obj_t * game_screen;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label6;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES
extern lv_obj_t * ui_p3d;
extern lv_obj_t * ui_dcs;
extern lv_obj_t * ui_f16;
extern lv_obj_t * ui_f18;
extern lv_obj_t * ui_f22;

// SCREEN: ui_Screen3
void sensor_screen_init(void);
extern lv_obj_t * sensor_screen;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES
extern lv_obj_t * ui_gyro;
extern lv_obj_t * ui_fc;

// SCREEN: ui_Screen4
void ui_config_screen_init(void);
extern lv_obj_t * ui_config_screen;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label18;
// CUSTOM VARIABLES
extern lv_obj_t * ui_yes;
extern lv_obj_t * ui_no;

// SCREEN: ui_Screen5
void red_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * red_screen;
extern lv_obj_t * ui_Container19;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
