// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
void ui_no_event(lv_event_t * e);
void ui_yes_event(lv_event_t * e);
void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 129);
    lv_obj_set_height(ui_Container11, 70);
    lv_obj_set_x(ui_Container11, -85);
    lv_obj_set_y(ui_Container11, 10);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container11, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container11, lv_color_hex(0xF55C19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "是");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 129);
    lv_obj_set_height(ui_Container12, 70);
    lv_obj_set_x(ui_Container12, 83);
    lv_obj_set_y(ui_Container12, 7);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container12, 11, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container12, lv_color_hex(0xF55C19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -4);
    lv_obj_set_y(ui_Label12, -8);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "否");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -16);
    lv_obj_set_y(ui_Label13, -74);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "是否开启航向罗盘");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -161);
    lv_obj_set_y(ui_Button4, -205);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 1);
    lv_obj_set_y(ui_Label18, 4);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "返回");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    ui_yes = ui_Container11;
    ui_no = ui_Container12;
    lv_obj_add_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE);
    
    lv_obj_set_style_bg_opa(ui_Container11, LV_OPA_COVER,LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container12, LV_OPA_COVER,LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_yes, ui_yes_event, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_no, ui_no_event, LV_EVENT_ALL, NULL);
}
void ui_yes_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {

        lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xF66D31), LV_PART_MAIN|LV_STATE_DEFAULT  );


        lv_obj_set_style_bg_color(ui_Container12, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT );
      //   lv_obj_set_style_bg_opa(ui_Container12, LV_OPA_COVER,LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
void ui_no_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {

        lv_obj_set_style_bg_color(ui_Container12, lv_color_hex(0xF66D31), LV_PART_MAIN|LV_STATE_DEFAULT  );
  

        lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN|LV_STATE_DEFAULT );
       // lv_obj_set_style_bg_opa(ui_Container11, LV_OPA_COVER,LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
