; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.20
framework = arduino

board = esp32-p4-evboard
board_build.mcu = esp32p4
; board = esp32-s3-devkitm-1


board_build.flash_mode = qio
build_flags = 
			-D BOARD_HAS_PSRAM
			; -Ilib/lvgl
			; -D LV_USE_DEMO_WIDGETS
			; -D LV_CONF_INCLUDE_SIMPLE
    		; -D LV_LVGL_H_INCLUDE_SIMPLE

lib_deps = 
	moononournation/GFX Library for Arduino@1.6.2
	olikraus/U8g2@2.35.9
	okalachev/MAVLink@^2.0.5
	lvgl/lvgl@^9.2.0
	; DCS-Skunkworks/dcs-bios@^0.3.10