
/** -------------------- By MiluoOffical 2026.02.02 --------------
 * @file red_screen.cpp
 * @date 2026-02-02
 * @note 本文件原本为 red_screen.c
 *       为了能在该处进行红屏操作和红屏进入/退出, 需要访问gfx类, 而gfx类为C++对象, 无法在c源文件中使用
 *       因此需要更名
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

extern "C" {
#include "core/lv_obj_pos.h"
#include "core/lv_refr.h"
#include "display/lv_display.h"
#include "ui.h"
#include "ui_helpers.h" // 为了 _ui_screen_change 函数
}
#include <Arduino_GFX_Library.h>

#include "gesdata.h"
#include "gesture-rgb.h"
#include "compass.h"
#include "radar-new.h"
#include "receive-mpu.h"
#include "receive-mavlink.h"

String inputString = "";
bool stringComplete = false;

ges_data_t ges_data_curr;


extern "C" int ges_show_type = 1;  //状态标记变量. 0代表LVGL显示中, 非0代表GFX显示中
static bool gfx_screen_updated = false;

volatile unsigned long start_time = 0;



uint16_t radar_scan_angle =0;

extern "C" void show_gesture(){

    drawGestureByData(ges_show_type, ges_data_curr, 0, 0);
    ges_show_type = 1; //初始刷到第一屏幕
    gfx_screen_updated = false; //需要多刷一次纯色屏, 这样才能覆盖刷新被lvgl绘制的脏区域
}


extern "C" void ges_show_handler(){
    radar_scan_angle = radar_scan_angle + 2;
    if(radar_scan_angle >= 360 ){
        radar_scan_angle = 0;
    }

    Serial.println("radar_scan_angle: " + String(radar_scan_angle));

    if(ges_show_type){
        if(!gfx_screen_updated){
            
            if(ges_show_type<=3){
                drawGestureByData(ges_show_type, ges_data_curr, 0, 0);
            }
            if(ges_show_type==4){
                ratateCompass(ges_data_curr.yaw, 0,0);
            }
            if(ges_show_type==5){
                rotatePointer(radar_scan_angle);
            }
            
            gfx_screen_updated = true;
        }
        
    }
    else{
        lv_timer_handler();
    }

}

extern "C" void update_gfx_screen(){
    gfx_screen_updated = false;
}

extern "C" void return_to_lvgl(){
    ges_show_type = 0;
    gfx_screen_updated = false;
    _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    lv_obj_update_layout(main_screen);
    lv_area_t mainArea = {
        .x1 = 0,
        .y1 = 0,
        .x2 = lv_obj_get_width(main_screen),
        .y2 = lv_obj_get_height(main_screen),
    };
    lv_obj_invalidate_area(main_screen, &mainArea);
    lv_refr_now(lv_display_get_default());
}


void refresh_mavlink_data(){
    // ges_data_curr = mavlink_receive_parse();
}

void refresh_mpu_data(){
    // ges_data_curr = receive_parse_mpu();
}

String getStringBetween(String data, String startStr, String endStr) {
    int startIndex = data.indexOf(startStr);
    if (startIndex == -1) return "";  // 起始字符串未找到
    
    startIndex += startStr.length();  // 移动到起始字符串之后
    
    int endIndex = data.indexOf(endStr, startIndex);
    if (endIndex == -1) return "";    // 结束字符串未找到
    
    return data.substring(startIndex, endIndex);
}

void serial_read_p3d(){
    if(ges_show_type==0){
        return;
    }
   // while(Serial.available()>0) {
    //     uint8_t c = Serial.read();
    //     Serial2.write(c);
    // }
    while(Serial.available()>0) {
        char inChar = (char)Serial.read();
        // Serial2.print(inChar);
        if (inChar == '/') {
          stringComplete = true;
        } else {
          inputString += inChar;
        }
        
    }
    
    if(stringComplete){
        
        String altitude_str = getStringBetween(inputString, "altitude:", ",");
        String bank_str = getStringBetween(inputString, "bank:", ",");
        String pitch_str = getStringBetween(inputString, "pitch:", ",");
        String air_speed = getStringBetween(inputString, "air_speed:", ",");
        String heading_str = getStringBetween(inputString, "heading:", ",");

        ges_data_curr.roll = bank_str.toInt();
        ges_data_curr.pitch = pitch_str.toInt();
        ges_data_curr.yaw = heading_str.toInt();
        ges_data_curr.altitude = altitude_str.toInt();
        ges_data_curr.air_speed = air_speed.toInt();

        inputString = "";
    }
}

void refresh_p3d_data(){
    serial_read_p3d();
}

