
/** -------------------- By MiluoOffical 2026.02.02 --------------
 * @file red_screen.cpp
 * @date 2026-02-02
 * @note 本文件原本为 red_screen.c
 *       为了能在该处进行红屏操作和红屏进入/退出, 需要访问gfx类, 而gfx类为C++对象, 无法在c源文件中使用
 *       因此需要更名
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

extern "C" {
#include "core/lv_obj_pos.h"
#include "core/lv_refr.h"
#include "display/lv_display.h"
#include "ui.h"
#include "ui_helpers.h" // 为了 _ui_screen_change 函数
}
#include <Arduino_GFX_Library.h>

#include "gesture-rgb.h"
#include "receive-mpu.h"
#include "receive-mavlink.h"

String inputString = "";
bool stringComplete = false;

ges_data_t ges_data_curr;

static int show_ges_status = false;
static bool ges_status_update = false;


extern "C" void show_gesture(){
    drawGestureByData(2, ges_data_curr, 0, 0);
    show_ges_status = true;
}

extern "C" void lvgl_custom_handler(){
    if(show_ges_status){
        if(!ges_status_update){
            drawGestureByData(2, ges_data_curr, 0, 0);
            ges_status_update = true;
        }
    }
    else{
        lv_timer_handler();
    }
}

extern "C" void clear_gesture(){
    show_ges_status = false;
    ges_status_update = false;
    _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    lv_obj_update_layout(main_screen);
    lv_area_t mainArea = {
        .x1 = 0,
        .y1 = 0,
        .x2 = lv_obj_get_width(main_screen),
        .y2 = lv_obj_get_height(main_screen),
    };
    lv_obj_invalidate_area(main_screen, &mainArea);
    lv_refr_now(lv_display_get_default());
}

extern "C" bool is_show_gesture(){
    return show_ges_status;
}

void refresh_mavlink_data(){
    ges_data_curr = mavlink_receive_parse();
}

void refresh_mpu_data(){
    ges_data_curr = receive_parse_mpu();
}

String getStringBetween(String data, String startStr, String endStr) {
    int startIndex = data.indexOf(startStr);
    if (startIndex == -1) return "";  // 起始字符串未找到
    
    startIndex += startStr.length();  // 移动到起始字符串之后
    
    int endIndex = data.indexOf(endStr, startIndex);
    if (endIndex == -1) return "";    // 结束字符串未找到
    
    return data.substring(startIndex, endIndex);
}

void serial_read_p3d(){
   // while(Serial.available()>0) {
    //     uint8_t c = Serial.read();
    //     Serial2.write(c);
    // }
    while(Serial.available()>0) {
        char inChar = (char)Serial.read();
        // Serial2.print(inChar);
        if (inChar == '/') {
          stringComplete = true;
        } else {
          inputString += inChar;
        }
        
    }
    
    if(stringComplete){
        
        String altitude_str = getStringBetween(inputString, "altitude:", ",");
        String bank_str = getStringBetween(inputString, "bank:", ",");
        String pitch_str = getStringBetween(inputString, "pitch:", ",");
        String air_speed = getStringBetween(inputString, "air_speed:", ",");
        String heading_str = getStringBetween(inputString, "heading:", ",");

        ges_data_curr.roll = bank_str.toInt();
        ges_data_curr.pitch = pitch_str.toInt();
        ges_data_curr.yaw = heading_str.toInt();
        ges_data_curr.altitude = altitude_str.toInt();
        ges_data_curr.air_speed = air_speed.toInt();
        // tft.fillScreen(TFT_BLACK);
        // tft.drawString("altitude:" + altitude_str, 0, 0, 4);
        // tft.drawString("bank:" + bank_str, 0, 50, 4);
        // tft.drawString("pitch:" + pitch_str, 0, 100, 4);
        // tft.drawString("heading:" + heading_str, 0, 150, 4);

        inputString = "";
    }
}

void refresh_p3d_data(){
    serial_read_p3d();
}

// extern "C" void red_screen_init(void){ //这个函数是C接口的 所以加上 extern "C"
//     red_screen = lv_obj_create(NULL);
//     lv_obj_remove_flag(red_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(red_screen, lv_color_hex(0xFA0303), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(red_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container19 = lv_obj_create(red_screen);
//     lv_obj_remove_style_all(ui_Container19);
//     lv_obj_set_width(ui_Container19, 100);
//     lv_obj_set_height(ui_Container19, 50);
//     lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
//     lv_obj_remove_flag(ui_Container19, lv_obj_flag_t (LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));      /// Flags

//     lv_obj_add_event_cb(red_screen, ui_event_bottom_slide_up, LV_EVENT_ALL, NULL);

// }
