
/** -------------------- By MiluoOffical 2026.02.02 --------------
 * @file red_screen.cpp
 * @date 2026-02-02
 * @note 本文件原本为 red_screen.c
 *       为了能在该处进行红屏操作和红屏进入/退出, 需要访问gfx类, 而gfx类为C++对象, 无法在c源文件中使用
 *       因此需要更名
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

extern "C" {
#include "core/lv_obj_pos.h"
#include "core/lv_refr.h"
#include "display/lv_display.h"
#include "ui.h"
#include "ui_helpers.h" // 为了 _ui_screen_change 函数
}
#include <Arduino_GFX_Library.h>

#include "gesture-rgb.h"
#include "receive-mpu.h"
#include "receive-mavlink.h"

String inputString = "";
bool stringComplete = false;

ges_data_t ges_data_curr;


extern "C" int ges_show_type = 0;  //状态标记变量. 0代表LVGL显示中, 非0代表GFX显示中
static bool gfx_screen_updated = false;

volatile unsigned long start_time = 0;

volatile int ges_init = 0;


extern "C" void show_gesture(){
    drawGestureByData(2, ges_data_curr, 0, 0);
    // show_ges_status = true;
    ges_show_type = 1; //初始刷到第一屏幕
    gfx_screen_updated = false; //需要多刷一次纯色屏, 这样才能覆盖刷新被lvgl绘制的脏区域
}


extern "C" void ges_show_handler(){
    Serial.println("ges_show_type: " + String(ges_show_type) + ", gfx_screen_updated: " + String(gfx_screen_updated) + ", " + String(millis()));
    
    if(millis() - start_time > 500) { // 每100ms刷新一次数据
        ges_data_curr.air_speed=ges_data_curr.air_speed+2;
        ges_data_curr.altitude=ges_data_curr.altitude+2;
        ges_data_curr.roll = ges_data_curr.roll+2;
        if(ges_data_curr.roll >350){
            ges_data_curr.roll = 0;
        }
        start_time = millis();
    }
    // if(ges_init==0){
    //     gestureInit(0,0);
    //     ges_init = 1;
    // }
    if(ges_show_type){
        if(!gfx_screen_updated){
            drawGestureByData(3, ges_data_curr, 0, 0);
            // switch (ges_show_type){
                // case 1:
                //     drawGestureByData(1, ges_data_curr, 0, 0);
                // break;
                // case 2:
                //     drawGestureByData(2, ges_data_curr, 0, 0);
                // break;
                // case 3:
                    // drawGestureByData(3, ges_data_curr, 0, 0);
                // break;
            // }
                gfx_screen_updated = true;
            // }
            
        }
    }
    else{
        lv_timer_handler();
    }

}

extern "C" void update_gfx_screen(){
    gfx_screen_updated = false;
}

extern "C" void return_to_lvgl(){
    ges_show_type = 0;
    gfx_screen_updated = false;
    _ui_screen_change(&main_screen, LV_SCR_LOAD_ANIM_FADE_ON, 1, 0, &main_screen_init);
    lv_obj_update_layout(main_screen);
    lv_area_t mainArea = {
        .x1 = 0,
        .y1 = 0,
        .x2 = lv_obj_get_width(main_screen),
        .y2 = lv_obj_get_height(main_screen),
    };
    lv_obj_invalidate_area(main_screen, &mainArea);
    lv_refr_now(lv_display_get_default());
}


void refresh_mavlink_data(){
    ges_data_curr = mavlink_receive_parse();
}

void refresh_mpu_data(){
    ges_data_curr = receive_parse_mpu();
}

String getStringBetween(String data, String startStr, String endStr) {
    int startIndex = data.indexOf(startStr);
    if (startIndex == -1) return "";  // 起始字符串未找到
    
    startIndex += startStr.length();  // 移动到起始字符串之后
    
    int endIndex = data.indexOf(endStr, startIndex);
    if (endIndex == -1) return "";    // 结束字符串未找到
    
    return data.substring(startIndex, endIndex);
}

void serial_read_p3d(){
   // while(Serial.available()>0) {
    //     uint8_t c = Serial.read();
    //     Serial2.write(c);
    // }
    while(Serial.available()>0) {
        char inChar = (char)Serial.read();
        // Serial2.print(inChar);
        if (inChar == '/') {
          stringComplete = true;
        } else {
          inputString += inChar;
        }
        
    }
    
    if(stringComplete){
        
        String altitude_str = getStringBetween(inputString, "altitude:", ",");
        String bank_str = getStringBetween(inputString, "bank:", ",");
        String pitch_str = getStringBetween(inputString, "pitch:", ",");
        String air_speed = getStringBetween(inputString, "air_speed:", ",");
        String heading_str = getStringBetween(inputString, "heading:", ",");

        ges_data_curr.roll = bank_str.toInt();
        ges_data_curr.pitch = pitch_str.toInt();
        ges_data_curr.yaw = heading_str.toInt();
        ges_data_curr.altitude = altitude_str.toInt();
        ges_data_curr.air_speed = air_speed.toInt();
        // tft.fillScreen(TFT_BLACK);
        // tft.drawString("altitude:" + altitude_str, 0, 0, 4);
        // tft.drawString("bank:" + bank_str, 0, 50, 4);
        // tft.drawString("pitch:" + pitch_str, 0, 100, 4);
        // tft.drawString("heading:" + heading_str, 0, 150, 4);

        inputString = "";
    }
}

void refresh_p3d_data(){
    serial_read_p3d();
}

// extern "C" void red_screen_init(void){ //这个函数是C接口的 所以加上 extern "C"
//     red_screen = lv_obj_create(NULL);
//     lv_obj_remove_flag(red_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
//     lv_obj_set_style_bg_color(red_screen, lv_color_hex(0xFA0303), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_bg_opa(red_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Container19 = lv_obj_create(red_screen);
//     lv_obj_remove_style_all(ui_Container19);
//     lv_obj_set_width(ui_Container19, 100);
//     lv_obj_set_height(ui_Container19, 50);
//     lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
//     lv_obj_remove_flag(ui_Container19, lv_obj_flag_t (LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));      /// Flags

//     lv_obj_add_event_cb(red_screen, ui_event_bottom_slide_up, LV_EVENT_ALL, NULL);

// }
