#include "../configui/global_config.h"

#ifndef RADAR_UI_CONFIG_H
#define RADAR_UI_CONFIG_H

#define RADAR_SP_W SCREEN_W_480
#define RADAR_SP_H SCREEN_H_480

#define RADAR_RADIUS (min(RADAR_SP_W, RADAR_SP_H)/2)

#define RADAR_SCALE_COLOR GREEN
#define RADAR_POINTER_COLOR GREEN
#define RADAR_TEXT_COLOR GREEN

#define CROSS_LINE_W 2
#define RADAR_POINTER_ANGLE 15
#define RADAR_SCALE_DOT_NUM 24
#define RADAR_SCALE_DOT_LEN 10

#endif